### ISSUE TITLE
Critical error if choose Sepolia network on swap page

### ISSUE THREAD

**Issue by alter-eggo** [balancer/frontend-v3#1013]
If choose sepolia network on swap page - we get critical "too many rerenders" error. 
it prob happens bc of empty sepolia tokens list

![Image](https://github.com/user-attachments/assets/d07d9541-7567-4d67-bcdd-f1033c8a3756)
![Image](https://github.com/user-attachments/assets/2dcc9e1e-d4c0-456e-b102-f324419f3535)

**Comment by neverm25** [comment]
@alter-eggo I found the reason for the issue.
It's because there are no tokens data for sepolia from graphql.

subgraph endpoint: https://api-v3.balancer.fi/graphql
operationName: "GetTokenPrices"

https://github.com/balancer/frontend-v3/blob/main/lib/modules/tokens/TokensProvider.tsx#L60-L63
