### ISSUE TITLE
CoW AMM pool support

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-v3#692]
https://balancer.fi/pools/cow

- [x] Fix pool details (issue with swap fee).
- [x] Add filter
- [x] Make add/removes work, new handler. - A
- [x] Fix light theme or hide toggle and force dark (ask pon for light theme) - G
- [x] Account for 'surplus' in APRs - A
- [x] Check with Pon about theme details, links out to CoW to learn more etc. - G
- [x] Replace featured pools with banner - G
- [x] Make /pools/cow work - G
- [x] [Moo](https://github.com/cowprotocol/cowswap/blob/develop/apps/cowswap-frontend/public/audio/success.mp3) instead of gong - A
- [x] Add surplus message instead of swap fee, it doesn't make sense to show 99% swap fee - P then A
- [x] Dust because of slippage on BPT - G
- [x] Missing weights - API issue @franzns 
- [x] Update cow token icon - @franzns @zekraken-bot
- [x] Add link to [Learn More](https://cow.fi/cow-amm) on the pool detail banner - P
- [x] Update active color for chart dropdown @uiuxxx 
![Screenshot 2024-07-26 at 10 38 19](https://github.com/user-attachments/assets/22cc2adf-a7e7-4128-aa9a-f42edcdcb0dd)
- [x] Don't allow cow theme on non-cow pools - A
- [x] Initial binding results in duplicate events in subgraph - @mendesfabio 
- [x] Add events are showing twice in the subgraph - @mendesfabio 
- [x] Link colors on the CoW theme are purple, doesn't look great - @uiuxxx 
- [x] Issues with parsing the tx hash when adding liquidity. This appears to only happen directly on execution. When navigating back, the data is visible - @agualis 
![Screenshot 2024-07-26 at 15 26 29](https://github.com/user-attachments/assets/ef1bc0af-c15d-4f4f-89a0-c2dc59d30812)
- [x] Get app to work within Safe app. @agualis 
- [x] Fix app errors when user enters the checksum address. @garethfuller 
- [x] Change 24 Hour fees to 24 hour surplus (see query below) @garethfuller
```
{
  poolGetPools(where: {poolTypeIn: [COW_AMM], tagNotIn:["BLACK_LISTED"]}) {
    id
    name
    chain
    categories
    dynamicData {
      totalLiquidity
      fees24h
      surplus24h
    }
  }
}
```
- [x] Hide the fees chart for CoW pools - @garethfuller 
- [x] Fix the volume and tvl snapshots for cow pools - @franzns 
- [x] Investigate how hard it would be to add snapshots for surplus to the api - @franzns 
- [ ] The moo sound appears to no be playing in full, have a look if this can be corrected - @uiuxxx 
- [x] Add the surplus snapshots chart to cow pools now that the data is in the api - @garethfuller 
- [x] On detail page, `How it Works` button should open a new tab, similar to the list page - @garethfuller 
- [x] Hide recent activity when wallet is not connected - @garethfuller 
![Screenshot 2024-07-30 at 14 34 42](https://github.com/user-attachments/assets/e0556306-be55-4adc-a0f5-535e8cc88cf3)
- [x] All pools are showing 0 liquidity providers - @franzns

**Comment by garethfuller** [comment]
@uiuxxx could you add context here about designs? i.e. light theme and any changes to banners etc.

**Comment by garethfuller** [comment]
@uiuxxx I tested the moo sounds and I don't hear it being cut off, sounds fine to me.

**Comment by agualis** [comment]
I also tested it several times and didn't cut off

**Comment by franzns** [comment]
Holders fixed:
```{
  "data": {
    "poolGetPool": {
      "address": "0x687728f6b21f1d4743a99f80c6fd344d4b693fc4",
      "type": "COW_AMM",
      "chain": "GNOSIS",
      "dynamicData": {
        "totalLiquidity": "21.87",
        "holdersCount": "2"
      }
    }
  }
}
