### ISSUE TITLE
V3 pool support

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-v3#694]
Add support for v3 pools. There are currently Sepolia pools to test against.

- [ ] Talk to Anastas about Sepolia - merge any fixes with main
- [ ] Test out sepolia (ask Fabio for tokens/faucet)
- [ ] Get v3 pool to show in pools list (talk to Franz)
- [ ] Get v3 pool page to render
- [ ] Get v3 pool actions (add/remove handlers)

**Comment by garethfuller** [comment]
@agualis I think we can close this ticket right? It's kind of a higher level milestone.

**Comment by agualis** [comment]
Closing ticket as suggested by @garethfuller
