### ISSUE TITLE
Replace 'My APR' with 'My pool share' in the My Liquidity module

### ISSUE THREAD

**Issue by uiuxxx** [balancer/frontend-v3#720]
Replace 'APR' range with 'My pool share' in the My Liquidity module on the Pool Detail page. 

This 'pool share' should be contextual to the tab it is on, e.g.: 
- On the 'Total' tab, it should be the user's total liquidity divided by total liquidity of the pool 
- On the Unstaked tab, it should be the user's total unstaked liquidity in this pool divided by the total liquidity of the pool. 

If there is a zero balance, display an 'n-dash' (–).

![Image](https://github.com/balancer/frontend-v3/assets/149399376/14e81ce9-868c-4ed9-8322-0debbae3414b)

**Comment by garethfuller** [comment]
Looks like this has been done. Re-open otherwise.
