### ISSUE TITLE
Mobile wallet buttons not working

### ISSUE THREAD

**Issue by garethfuller** [balancer/frontend-v3#875]
Links to connect metamask/rainbow etc don't work on mobile.

https://discord.com/channels/638460494168064021/1266135985935351962/1266195330240741427

**Comment by agualis** [comment]
Tested from browser within Rabby android app: 


![Image](https://github.com/user-attachments/assets/609cf7e6-86a0-4724-8a55-153e463d1729)

**Comment by agualis** [comment]
@garethfuller @alter-eggo 
Could you test [this setup](https://github.com/balancer/frontend-v3/pull/917) in your iphones?
It should fix some dissconection issues and it's working in my android. 
Note that I moved `injectedWallet` (displayed as `Browser Wallet` in the UI) to the end of the list cause I would not work in most of the mobile scenarios. 
Another important detail is that it is not clear the list of recommended wallets in mobile has horizontal scroll. If possible, we should add some tip for that: 

![Image](https://github.com/user-attachments/assets/85a7d675-3cb4-495a-94a8-49e7c1458c57)
